export const  INCREMENT_ACTION =  "INCREMENT_ACTION"
export const DECREMENT_ACTION = "DECREMENT_ACTION"
export const USER_LOGIN_ACTION = "USER_LOGIN_ACTION"
export const SAGA_LOGIN_ACTION = "SAGA_LOGIN_ACTION" 
export const FORM_LOGIN_DATA_ACTION = "FORM_LOGIN_DATA_ACTION"
export const FORM_RESPONSE_DATA_ACTION = "FORM_RESPONSE_DATA_ACTION"
export const CONFIG_RESPONSE_ACTION = "CONFIG_RESPONSE_ACTION"
export const CONFIG_SETTINGS_ACTION = "CONFIG_SETTINGS_ACTION"
export const ERROR_ACTION = 'ERROR_ACTION';
export const LOADER_ACTION = 'LOADER_ACTION';




